import { afterAll, afterEach } from 'vitest';
import fs from 'node:fs/promises';
import path from 'node:path';
import { ConfigService } from '../src/services/ConfigService.js';

// Ensure GIGAFLAIR_MASTER_KEY is set for all tests
if (!process.env.GIGAFLAIR_MASTER_KEY) {
    process.env.GIGAFLAIR_MASTER_KEY = 'test_master_key_for_vitest_only_do_not_use_in_production';
}

afterEach(async () => {
    // Reset singleton after each test to prevent cross-test contamination
    ConfigService._resetInstance();

    // Clean up temporary config files generated by tests
    const testsDir = path.join(process.cwd(), 'tests');
    try {
        const files = await fs.readdir(testsDir);
        for (const file of files) {
            if (file.startsWith('test-config-') && file.endsWith('.json')) {
                await fs.unlink(path.join(testsDir, file)).catch(() => { });
            }
        }
    } catch { }

    // Clean up temporary master keys
    try {
        await fs.unlink(path.join(process.cwd(), '.master_key')).catch(() => { });
    } catch { }
    try {
        await fs.unlink(path.join(testsDir, '.master_key')).catch(() => { });
    } catch { }
});

afterAll(async () => {
    // Final cleanup pass
    const testsDir = path.join(process.cwd(), 'tests');
    try {
        const files = await fs.readdir(testsDir);
        for (const file of files) {
            if (file.startsWith('test-config-') && file.endsWith('.json')) {
                await fs.unlink(path.join(testsDir, file)).catch(() => { });
            }
        }
    } catch { }
});
